### Задача (варіант 1)

**Ієрархія:** p = 3, повна, m = (4, 3, 3)

<img src="images/lab_2_hierarchy.png" width=256>

**Метод розрахунку глобальних ваг:** дистрибутивний, ГВБВПА

*Методи аналізу альтернатив рішень на основі ієрархічної моделі критеріїв (МАІ, analytic hierarchy process, AHP)* складаються з наступних чотирьох загальних етапів:

1. Побудова ієрархічної моделі критеріїв, цілей та інших факторів, які впливають на головну ціль прийняття рішення; побудова множини альтернативних варіантів рішень.

2. Отримання суджень експертів щодо парних порівнянь елементів одного рівня ієрархії відносно спільного елементу вищого рівня. Парні порівняння проводяться у вибраній шкалі і за результатами будуються матриці парних порівнянь (МПП), які є обернено симетричними.

3. Математична обробка суджень експертів:
   * розрахунок локальних ваг елементів кожного рівня ієрархії відповідно до батьківських елементів вищого рівня на основі МПП; побудова локальних ранжувань;
   * аналіз узгодженості експертних оцінок;
   * розрахунок глобальних ваг елементів ієрархії відносно головної цілі прийняття рішення, використовуючи методи агрегування; побудова ранжування на основі глобальних ваг.

4. Аналіз чутливості отриманих ранжувань.

Постановка задачі:

**Дано:** 
 * $A = \{A_i | i = 1, \dots, N \}$ - множина альтернативних варіантів рішень;
 * $C = \{C_j | j = 1, \dots, M \}$ - множина критеріїв оцінювання альтернатив;
 * $a_{ij}$ - ненормована вага льтернативи $A_i$ за критерієм $C_j$;
 * $w_j^C$ - вага критерію $C_j, \sum_{j=1}^{M} w_j^C = 1$

**Потрібно:**
 * знайти глобальні ваги $w_i^{глоб}$ альтернатив $A_i, i = 1, \dots, N$

***Методи аналізу альтернатив рішень на основі ієрархічної моделі критеріїв (МАІ, analytic hierarchy process, AHP) складаються з наступних чотирьох загальних етапів:***


***1.*** Побудова ієрархічної моделі критеріїв, цілей та інших факторів, які впливають на головну ціль прийняття рішення; побудова множини альтернативних варіантів рішень - цей етап зроблено за нас - ієрархія (4, 3, 3) (тобто (1, 4, 3, 3) враховуючи мету)

In [1]:
import numpy as np
# put some fixed seed for reproducibility of the results
np.random.seed(42)

In [2]:
# we work with fully connected hierarcy, its architecture is defined by number of nodes per layer
# All layers but the last 'layers[:-1]' - creiterions
layers = [1, 4, 3, 3]
# last layer - 'layers[-1]' - alternatives
num_alternatives = layers[-1]
# number of layers
p = len(layers) - 1

Функція для генерування коректної матриці парних порівнянь для мультиплікативної групи

In [3]:
def generate_matched_matrix(dim, low=1, high=10):
    """
    Generates matched multiplicational matrix mmp i.e. \forall i \in [0, n-1]: mpp[i][i] = 1;
    \forall i, j i \neq j: mpp[i][j] = 1 / mpp[j][i]
    Returns 2D matched matrix of shape (dim, dim)
    """
    mmp = np.zeros((dim, dim))
    temp = np.random.randint(low, high, size=dim).astype(float)
    powers = np.random.choice(3, size=dim, p=[0.5, 0, 0.5]) - 1
    mmp[0, :] = np.power(temp, powers)
    j = 0
    for i in range(1, dim):
        mmp[i, j] = 1 / mmp[j, i]
    for i in range(1, dim):
        for j in range(1, dim):
            mmp[i, j] = mmp[i, 0] * mmp[0, j]
    mmp[0][0] = 1
    return mmp

# Data generation

***2.*** Отримання суджень експертів щодо парних порівнянь елементів одного рівня ієрархії відносно спільного елементу вищого рівня. Парні порівняння проводяться у вибраній шкалі і за результатами будуються матриці парних порівнянь (МПП), які є обернено симетричними.

Генеруємо матриці парних порівнянь - замість опитування експертів.

Наша ієрархія - (4, 3, 3), фактично працюємо з ієрархією (1, 4, 3, 3). Тобто експертами формуються наступні матриці парних порівнянь
* 4x4x1 - парні порівняння 4 критеріїв відносно 1 критерію (мети)
* 3x3x4 - парні порівняння 3 підкритеріїв відносно 4 критеріїв
* 3х3х3 - парні порівняння 3 альтернатив відносно 3 підкритеріїв

Отримані дані об'єднаємо в список.

In [4]:
# generally speaking, number of nodes can vary from layer to layer, so further we use nested lists,
# not a np.array

D = []
for idx_curr in range(1, len(layers)):
    d = np.empty((layers[idx_curr], layers[idx_curr], layers[idx_curr - 1]))
    for i in range(layers[idx_curr - 1]):
        mpp = generate_matched_matrix(layers[idx_curr])
        d[:, :, i] = mpp
    D.append(d)

# display shapes and values of generated MPPs
for mpp in D:
    print(mpp.shape)
    print(mpp)
    print("*" * 80)

(4, 4, 1)
[[[1.00e+00]
  [2.50e-01]
  [1.25e-01]
  [5.00e+00]]

 [[4.00e+00]
  [1.00e+00]
  [5.00e-01]
  [2.00e+01]]

 [[8.00e+00]
  [2.00e+00]
  [1.00e+00]
  [4.00e+01]]

 [[2.00e-01]
  [5.00e-02]
  [2.50e-02]
  [1.00e+00]]]
********************************************************************************
(3, 3, 4)
[[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
  [1.25000000e-01 2.00000000e+00 1.00000000e+00 3.33333333e-01]
  [8.00000000e+00 2.00000000e-01 3.33333333e-01 7.00000000e+00]]

 [[8.00000000e+00 5.00000000e-01 1.00000000e+00 3.00000000e+00]
  [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
  [6.40000000e+01 1.00000000e-01 3.33333333e-01 2.10000000e+01]]

 [[1.25000000e-01 5.00000000e+00 3.00000000e+00 1.42857143e-01]
  [1.56250000e-02 1.00000000e+01 3.00000000e+00 4.76190476e-02]
  [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]]]
********************************************************************************
(3, 3, 3)
[[[1.00000

In [28]:
# generate weight of each criteria on the each layer
# again since number of criteria may vary from layer to layer we use Python's list to keep them
criteria_weights_lst = []
for num_of_crit in layers[:-1]:
    tmp = np.random.rand(num_of_crit)
    tmp /= np.linalg.norm(tmp, ord=1)
    criteria_weights_lst.append(tmp)

print("Criteria weights in given hierarchy:")
for criteria_weights in criteria_weights_lst:
    print(criteria_weights)

Criteria weights in given hierarchy:
[1.]
[0.05281096 0.19877981 0.11060354 0.63780569]
[0.34938423 0.27384693 0.37676885]


***3.*** Математична обробка суджень експертів:

* розрахунок локальних ваг елементів кожного рівня ієрархії відповідно до батьківських елементів вищого рівня на основі МПП; побудова локальних ранжувань;
* аналіз узгодженості експертних оцінок;
* розрахунок глобальних ваг елементів ієрархії відносно головної цілі прийняття рішення, використовуючи методи агрегування; побудова ранжування на основі глобальних ваг.

Обраховуємо локальні ваги використовуючи підхід EM з попередньої лабораторної роботи.

**ЕМ метод** Згідно цього метода вектором ваг є власний вектор МПП, що відповідає її найбільшому власному числу. Тобто кожна МПП буде замінена вектором тієї ж розмірності, що і МПП. Отже на виході функції мусимо отримати список тензорів наступної розмірності:

* 4х1
* 3х1
* 3х1

In [24]:
def _get_main_w_v_power(mat):
    """
    Computes main eigenvalue and main eigenvector.
    return: main eigenvalue and eigenvector
    """
    x = np.ones(mat.shape[0])
    x /= np.linalg.norm(x, ord=1)
    k = 30
    D = mat
    for idx in range(k):
        l = np.linalg.norm(np.dot(D, x), ord=1)
        x = np.dot(D, x) / l
    return l, x

def calculate_local(D):
    """
    D: list of rank 3 tensors - MPPs - of shape (n_curr, n_curr, n_prev)
    return: 
    """
    # create list which we will return
    res = []
    for i in range(len(D)):
        res.append(np.empty(D[i].shape[1:]))
    # for each set of MPP for current layer
    for idx_mpps_group in range(len(D)):
        # we iterate over the last, 2nd dimension
        for idx_mpp in range(D[idx_mpps_group].shape[-1]):
            mpp = D[idx_mpps_group][:, :, idx_mpp]
            _, v_max = _get_main_w_v_power(mpp)
            res[idx_mpps_group][:, idx_mpp] = v_max
    return res
local_weights = calculate_local(D)
local_weights

[array([[0.07575758],
        [0.3030303 ],
        [0.60606061],
        [0.01515152]]),
 array([[0.10958904, 0.15384615, 0.2       , 0.24137931],
        [0.87671233, 0.07692308, 0.2       , 0.72413793],
        [0.01369863, 0.76923077, 0.6       , 0.03448276]]),
 array([[0.09803922, 0.42857143, 0.70588235],
        [0.88235294, 0.14285714, 0.11764706],
        [0.01960784, 0.42857143, 0.17647059]])]

In [25]:
# check if we received normed local weights - compute sums of columns
for d in local_weights:
    print(d.shape)
    for idx in range(d.shape[-1]):
        print(f"{idx} -> sum == {np.sum(d[:, idx])}")

(4, 1)
0 -> sum == 1.0
(3, 4)
0 -> sum == 1.0
1 -> sum == 0.9999999999999999
2 -> sum == 1.0
3 -> sum == 1.0
(3, 3)
0 -> sum == 1.0
1 -> sum == 1.0
2 -> sum == 1.0


Отже наразі отримали локальні ваги $a_{ij}$ критеріїв/альтернатив(на останньому рівні) відносно батьківських елементів вищого рівня.

# Methods for finding global normed weights of alternatives

In [7]:
# distributive synthesis approach
def distributed_synthesis(w_crit, v):
    """
    Computes global weights
    """
    n, m = v.shape
    w_glob = np.empty(n)
    for i in range(n):
        # compute 'w_globe' components one by one
        r = v[i, :] / np.sum(v[:, i])
        r = r.reshape(m, 1)
        print("w_crit.shape =", w_crit.shape)
        print("r.shape =", r.shape)
        w_glob[i] = np.dot(w_crit.T, r)
    return w_glob

In [8]:
print(distributed_synthesis(w_crit, v).shape)
print(distributed_synthesis(w_crit, v))

NameError: name 'w_crit' is not defined

In [ ]:
w_glob = distributed_synthesis(w_crit, v)
print(np.sum(w_glob))

In [ ]:
# distributive synthesis approach
def distributive_synthesis_step()